---
development:
  dialect: postgres
  database: goesb_development
  user: postgres
  password: postgres
  host: 127.0.0.1
  pool: 5432

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/goesb_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/goesb_production?sslmode=disable"}}
